/* eslint-disable */
/**************************************************
 * styleClass names for Utility Styles
 *************************************************/
const UtilityClasses = {
  DEV_BORDER: "devBorder",

  /**************************************************
   * Alignment
   *************************************************/
  ALIGNMENT: {
    ALIGN_ITEMS_START: "alignItemsStart",
    ALIGN_ITEMS_END: "alignItemsEnd",
    ALIGN_ITEMS_CENTER: "alignItemsCenter",
    ALIGN_ITEMS_BASELINE: "alignItemsBaseline",
    ALIGN_ITEMS_STRETCH: "alignItemsStretch",

    ALIGN_CONTENT_START: "alignContentStart",
    ALIGN_CONTENT_END: "alignContentEnd",
    ALIGN_CONTENT_CENTER: "alignContentCenter",
    ALIGN_CONTENT_BETWEEN: "alignContentBetween",
    ALIGN_CONTENT_AROUND: "alignContentAround",
    ALIGN_CONTENT_STRETCH: "alignContentStretch",

    ALIGN_SELF_AUTO: "alignSelfAuto",
    ALIGN_SELF_START: "alignSelfStart",
    ALIGN_SELF_END: "alignSelfEnd",
    ALIGN_SELF_CENTER: "alignSelfCenter",
    ALIGN_SELF_BASELINE: "alignSelfBaseline",
    ALIGN_SELF_STRETCH: "alignSelfStretch",

    JUSTIFY_CONTENT_CENTER: "justifyContentCenter",
    JUSTIFY_CONTENT_FLEX_START: "justifyContentFlexStart",
    JUSTIFY_CONTENT_FLEX_END: "justifyContentFlexEnd",
    JUSTIFY_CONTENT_SPACE_BETWEEN: "justifyContentSpaceBetween",
    JUSTIFY_CONTENT_SPACE_AROUND: "justifyContentSpaceAround",
    JUSTIFY_CONTENT_SPACE_EVENLY: "justifyContentSpaceEvenly",
    SM: {
      ALIGN_ITEMS_START: "smAlignItemsStart",
      ALIGN_ITEMS_END: "smAlignItemsEnd",
      ALIGN_ITEMS_CENTER: "smAlignItemsCenter",
      ALIGN_ITEMS_BASELINE: "smAlignItemsBaseline",
      ALIGN_ITEMS_STRETCH: "smAlignItemsStretch",

      ALIGN_CONTENT_START: "smAlignContentStart",
      ALIGN_CONTENT_END: "smAlignContentEnd",
      ALIGN_CONTENT_CENTER: "smAlignContentCenter",
      ALIGN_CONTENT_BETWEEN: "smAlignContentBetween",
      ALIGN_CONTENT_AROUND: "smAlignContentAround",
      ALIGN_CONTENT_STRETCH: "smAlignContentStretch",

      ALIGN_SELF_AUTO: "smAlignSelfAuto",
      ALIGN_SELF_START: "smAlignSelfStart",
      ALIGN_SELF_END: "smAlignSelfEnd",
      ALIGN_SELF_CENTER: "smAlignSelfCenter",
      ALIGN_SELF_BASELINE: "smAlignSelfBaseline",
      ALIGN_SELF_STRETCH: "smAlignSelfStretch",

      JUSTIFY_CONTENT_CENTER: "smJustifyContentCenter",
      JUSTIFY_CONTENT_FLEX_START: "smJustifyContentFlexStart",
      JUSTIFY_CONTENT_FLEX_END: "smJustifyContentFlexEnd",
      JUSTIFY_CONTENT_SPACE_BETWEEN: "smJustifyContentSpaceBetween",
      JUSTIFY_CONTENT_SPACE_AROUND: "smJustifyContentSpaceAround",
      JUSTIFY_CONTENT_SPACE_EVENLY: "smJustifyContentSpaceEvenly",
    },
    MD: {
      ALIGN_ITEMS_START: "mdAlignItemsStart",
      ALIGN_ITEMS_END: "mdAlignItemsEnd",
      ALIGN_ITEMS_CENTER: "mdAlignItemsCenter",
      ALIGN_ITEMS_BASELINE: "mdAlignItemsBaseline",
      ALIGN_ITEMS_STRETCH: "mdAlignItemsStretch",

      ALIGN_CONTENT_START: "mdAlignContentStart",
      ALIGN_CONTENT_END: "mdAlignContentEnd",
      ALIGN_CONTENT_CENTER: "mdAlignContentCenter",
      ALIGN_CONTENT_BETWEEN: "mdAlignContentBetween",
      ALIGN_CONTENT_AROUND: "mdAlignContentAround",
      ALIGN_CONTENT_STRETCH: "mdAlignContentStretch",

      ALIGN_SELF_AUTO: "mdAlignSelfAuto",
      ALIGN_SELF_START: "mdAlignSelfStart",
      ALIGN_SELF_END: "mdAlignSelfEnd",
      ALIGN_SELF_CENTER: "mdAlignSelfCenter",
      ALIGN_SELF_BASELINE: "mdAlignSelfBaseline",
      ALIGN_SELF_STRETCH: "mdAlignSelfStretch",

      JUSTIFY_CONTENT_CENTER: "mdJustifyContentCenter",
      JUSTIFY_CONTENT_FLEX_START: "mdJustifyContentFlexStart",
      JUSTIFY_CONTENT_FLEX_END: "mdJustifyContentFlexEnd",
      JUSTIFY_CONTENT_SPACE_BETWEEN: "mdJustifyContentSpaceBetween",
      JUSTIFY_CONTENT_SPACE_AROUND: "mdJustifyContentSpaceAround",
      JUSTIFY_CONTENT_SPACE_EVENLY: "mdJustifyContentSpaceEvenly",
    },
    LG: {
      ALIGN_ITEMS_START: "lgAlignItemsStart",
      ALIGN_ITEMS_END: "lgAlignItemsEnd",
      ALIGN_ITEMS_CENTER: "lgAlignItemsCenter",
      ALIGN_ITEMS_BASELINE: "lgAlignItemsBaseline",
      ALIGN_ITEMS_STRETCH: "lgAlignItemsStretch",

      ALIGN_CONTENT_START: "lgAlignContentStart",
      ALIGN_CONTENT_END: "lgAlignContentEnd",
      ALIGN_CONTENT_CENTER: "lgAlignContentCenter",
      ALIGN_CONTENT_BETWEEN: "lgAlignContentBetween",
      ALIGN_CONTENT_AROUND: "lgAlignContentAround",
      ALIGN_CONTENT_STRETCH: "lgAlignContentStretch",

      ALIGN_SELF_AUTO: "lgAlignSelfAuto",
      ALIGN_SELF_START: "lgAlignSelfStart",
      ALIGN_SELF_END: "lgAlignSelfEnd",
      ALIGN_SELF_CENTER: "lgAlignSelfCenter",
      ALIGN_SELF_BASELINE: "lgAlignSelfBaseline",
      ALIGN_SELF_STRETCH: "lgAlignSelfStretch",

      JUSTIFY_CONTENT_CENTER: "lgJustifyContentCenter",
      JUSTIFY_CONTENT_FLEX_START: "lgJustifyContentFlexStart",
      JUSTIFY_CONTENT_FLEX_END: "lgJustifyContentFlexEnd",
      JUSTIFY_CONTENT_SPACE_BETWEEN: "lgJustifyContentSpaceBetween",
      JUSTIFY_CONTENT_SPACE_AROUND: "lgJustifyContentSpaceAround",
      JUSTIFY_CONTENT_SPACE_EVENLY: "lgJustifyContentSpaceEvenly",
    },
    XL: {
      ALIGN_ITEMS_START: "xlAlignItemsStart",
      ALIGN_ITEMS_END: "xlAlignItemsEnd",
      ALIGN_ITEMS_CENTER: "xlAlignItemsCenter",
      ALIGN_ITEMS_BASELINE: "xlAlignItemsBaseline",
      ALIGN_ITEMS_STRETCH: "xlAlignItemsStretch",

      ALIGN_CONTENT_START: "xlAlignContentStart",
      ALIGN_CONTENT_END: "xlAlignContentEnd",
      ALIGN_CONTENT_CENTER: "xlAlignContentCenter",
      ALIGN_CONTENT_BETWEEN: "xlAlignContentBetween",
      ALIGN_CONTENT_AROUND: "xlAlignContentAround",
      ALIGN_CONTENT_STRETCH: "xlAlignContentStretch",

      ALIGN_SELF_AUTO: "xlAlignSelfAuto",
      ALIGN_SELF_START: "xlAlignSelfStart",
      ALIGN_SELF_END: "xlAlignSelfEnd",
      ALIGN_SELF_CENTER: "xlAlignSelfCenter",
      ALIGN_SELF_BASELINE: "xlAlignSelfBaseline",
      ALIGN_SELF_STRETCH: "xlAlignSelfStretch",

      JUSTIFY_CONTENT_CENTER: "xlJustifyContentCenter",
      JUSTIFY_CONTENT_FLEX_START: "xlJustifyContentFlexStart",
      JUSTIFY_CONTENT_FLEX_END: "xlJustifyContentFlexEnd",
      JUSTIFY_CONTENT_SPACE_BETWEEN: "xlJustifyContentSpaceBetween",
      JUSTIFY_CONTENT_SPACE_AROUND: "xlJustifyContentSpaceAround",
      JUSTIFY_CONTENT_SPACE_EVENLY: "xlJustifyContentSpaceEvenly",
    },
    XXL: {
      ALIGN_ITEMS_START: "xxlAlignItemsStart",
      ALIGN_ITEMS_END: "xxlAlignItemsEnd",
      ALIGN_ITEMS_CENTER: "xxlAlignItemsCenter",
      ALIGN_ITEMS_BASELINE: "xxlAlignItemsBaseline",
      ALIGN_ITEMS_STRETCH: "xxlAlignItemsStretch",

      ALIGN_CONTENT_START: "xxlAlignContentStart",
      ALIGN_CONTENT_END: "xxlAlignContentEnd",
      ALIGN_CONTENT_CENTER: "xxlAlignContentCenter",
      ALIGN_CONTENT_BETWEEN: "xxlAlignContentBetween",
      ALIGN_CONTENT_AROUND: "xxlAlignContentAround",
      ALIGN_CONTENT_STRETCH: "xxlAlignContentStretch",

      ALIGN_SELF_AUTO: "xxlAlignSelfAuto",
      ALIGN_SELF_START: "xxlAlignSelfStart",
      ALIGN_SELF_END: "xxlAlignSelfEnd",
      ALIGN_SELF_CENTER: "xxlAlignSelfCenter",
      ALIGN_SELF_BASELINE: "xxlAlignSelfBaseline",
      ALIGN_SELF_STRETCH: "xxlAlignSelfStretch",

      JUSTIFY_CONTENT_CENTER: "xxlJustifyContentCenter",
      JUSTIFY_CONTENT_FLEX_START: "xxlJustifyContentFlexStart",
      JUSTIFY_CONTENT_FLEX_END: "xxlJustifyContentFlexEnd",
      JUSTIFY_CONTENT_SPACE_BETWEEN: "xxlJustifyContentSpaceBetween",
      JUSTIFY_CONTENT_SPACE_AROUND: "xxlJustifyContentSpaceAround",
      JUSTIFY_CONTENT_SPACE_EVENLY: "xxlJustifyContentSpaceEvenly",
    },
  },

  /**************************************************
   * Background
   *************************************************/
  BG: {
    BG_BLACK: "bgBlack",
    BG_WHITE: "bgWhite",
    BG_TRANSPARENT: "bgTransparent",

    BG_PRIMARY: "bgPrimary",
    BG_PRIMARY_LIGHT: "bgPrimaryLight",
    BG_PRIMARY_DARK: "bgPrimaryDark",

    BG_SECONDARY: "bgSecondary",
    BG_SECONDARY_LIGHT: "bgSecondaryLight",
    BG_SECONDARY_DARK: "bgSecondaryDark",

    BG_SUCCESS: "bgSuccess",
    BG_SUCCESS_LIGHT: "bgSuccessLight",
    BG_SUCCESS_DARK: "bgSuccessDark",

    BG_ERROR: "bgError",
    BG_ERROR_LIGHT: "bgErrorLight",
    BG_ERROR_DARK: "bgErrorDark",

    BG_WARNING: "bgWarning",
    BG_WARNING_LIGHT: "bgWarningLight",
    BG_WARNING_DARK: "bgWarningDark",

    BG_INFO: "bgInfo",
    BG_INFO_LIGHT: "bgInfoLight",
    BG_INFO_DARK: "bgInfoDark",

    BG_GREY_50: "bgGrey50",
    BG_GREY_100: "bgGrey100",
    BG_GREY_200: "bgGrey200",
    BG_GREY_300: "bgGrey300",
    BG_GREY_400: "bgGrey400",
    BG_GREY_500: "bgGrey500",
    BG_GREY_600: "bgGrey600",
    BG_GREY_700: "bgGrey700",
    BG_GREY_800: "bgGrey800",
    BG_GREY_900: "bgGrey900",
    BG_GREY_A100: "bgGreyA100",
    BG_GREY_A200: "bgGreyA200",
    BG_GREY_A400: "bgGreyA400",
    BG_GREY_A700: "bgGreyA700",

    BG_DOT_GRID_1: "bgDotGrid1",
    BG_DOT_GRID_2: "bgDotGrid2",
    BG_DOT_GRID_3: "bgDotGrid3",
    BG_DOT_GRID_4: "bgDotGrid4",
    BG_DOT_GRID_5: "bgDotGrid5",

    BG_SQUARE_GRID_1: "bgSquareGrid1",
    BG_SQUARE_GRID_2: "bgSquareGrid2",
    BG_SQUARE_GRID_3: "bgSquareGrid3",
    BG_SQUARE_GRID_4: "bgSquareGrid4",
    BG_SQUARE_GRID_5: "bgSquareGrid5",

    BG_GRAPH: "bgGraph",
    BG_ISOMETRIC_GRID: "bgIsometricGrid",
  },
  /**************************************************
   * Gradient
   *************************************************/
  GRADIENT: {
    LINEAR: {
      TO_BOTTOM: "gradientLinearToBottom",
      TO_TOP: "gradientLinearToTop",
      TO_RIGHT: "gradientLinearToRight",
      TO_LEFT: "gradientLinearToLeft",
      TO_BOTTOM_RIGHT: "gradientLinearToBottomRight",
      TO_BOTTOM_LEFT: "gradientLinearToBottomLeft",
      TO_TOP_RIGHT: "gradientLinearToTopRight",
      TO_TOP_LEFT: "gradientLinearToTopLeft",
    },
    RADIAL: {
      CIRCLE: "gradientRadialCircle",
      ELLIPSE: "gradientRadialEllipse",
      CLOSEST_SIDE: "gradientRadialClosestSide",
      CLOSEST_CORNER: "gradientRadialClosestCorner",
      FARTHEST_SIDE: "gradientRadialFarthestSide",
      FARTHEST_CORNER: "gradientRadialFarthestCorner",
    },
    REPEAT: {
      REPEAT: "gradientRepeat",
      REPEAT_X: "gradientRepeatX",
      REPEAT_Y: "gradientRepeatY",
      NO_REPEAT: "gradientNoRepeat",
      ROUND: "gradientRound",
      COVER: "gradientCover",
      CONTAIN: "gradientContain",
    },
    CONIC: {
      FROM_TOP: "gradientConicFromTop",
      FROM_RIGHT: "gradientConicFromRight",
      FROM_BOTTOM: "gradientConicFromBottom",
      FROM_LEFT: "gradientConicFromLeft",
      FROM_TOP_RIGHT: "gradientConicFromTopRight",
      FROM_TOP_LEFT: "gradientConicFromTopLeft",
      FROM_BOTTOM_RIGHT: "gradientConicFromBottomRight",
      FROM_BOTTOM_LEFT: "gradientConicFromBottomLeft",
    },
  },

  /**************************************************
   * Border
   *************************************************/
  BORDER: {
    BORDER: "border",
    BORDER_0: "border0",

    BORDER_TOP: "borderTop",
    BORDER_TOP_0: "borderTop0",

    BORDER_END: "borderEnd",
    BORDER_END_0: "borderEnd0",
    // BORDER_RIGHT: "borderRight",
    // BORDER_RIGHT_0: "borderRight0",

    BORDER_BOTTOM: "borderBottom",
    BORDER_BOTTOM_0: "borderBottom0",

    BORDER_START: "borderStart",
    BORDER_START_0: "borderStart0",
    // BORDER_LEFT: "borderLeft",
    // BORDER_LEFT_0: "borderLeft0",

    BORDER_PRIMARY: "borderPrimary",
    BORDER_PRIMARY_LIGHT: "borderPrimaryLight",
    BORDER_PRIMARY_DARK: "borderPrimaryDark",

    BORDER_SECONDARY: "borderSecondary",
    BORDER_SECONDARY_LIGHT: "borderSecondaryLight",
    BORDER_SECONDARY_DARK: "borderSecondaryDark",

    BORDER_SUCCESS: "borderSuccess",
    BORDER_SUCCESS_LIGHT: "borderSuccessLight",
    BORDER_SUCCESS_DARK: "borderSuccessDark",

    BORDER_ERROR: "borderError",
    BORDER_ERROR_LIGHT: "borderErrorLight",
    BORDER_ERROR_DARK: "borderErrorDark",

    BORDER_WARNING: "borderWarning",
    BORDER_WARNING_LIGHT: "borderWarningLight",
    BORDER_WARNING_DARK: "borderWarningDark",

    BORDER_INFO: "borderInfo",
    BORDER_INFO_LIGHT: "borderInfoLight",
    BORDER_INFO_DARK: "borderInfoDark",

    BORDER_GREY_50: "borderGrey50",
    BORDER_GREY_100: "borderGrey100",
    BORDER_GREY_200: "borderGrey200",
    BORDER_GREY_300: "borderGrey300",
    BORDER_GREY_400: "borderGrey400",
    BORDER_GREY_500: "borderGrey500",
    BORDER_GREY_600: "borderGrey600",
    BORDER_GREY_700: "borderGrey700",
    BORDER_GREY_800: "borderGrey800",
    BORDER_GREY_900: "borderGrey900",
    BORDER_GREY_A100: "borderGreyA100",
    BORDER_GREY_A200: "borderGreyA200",
    BORDER_GREY_A400: "borderGreyA400",
    BORDER_GREY_A700: "borderGreyA700",

    BORDER_BLACK: "borderBlack",
    BORDER_WHITE: "borderWhite",

    BORDER_1: "border1",
    BORDER_2: "border2",
    BORDER_3: "border3",
    BORDER_4: "border4",
    BORDER_5: "border5",

    BORDER_ROUNDED: "borderRounded",
    BORDER_ROUNDED_0: "borderRounded0",
    BORDER_ROUNDED_1: "borderRounded1",
    BORDER_ROUNDED_2: "borderRounded2",
    BORDER_ROUNDED_3: "borderRounded3",
    BORDER_ROUNDED_4: "borderRounded4",
    BORDER_ROUNDED_5: "borderRounded5",
    BORDER_ROUNDED_CIRCLE: "borderRoundedCircle",
    BORDER_ROUNDED_PILL: "borderRoundedPill",

    BORDER_ROUNDED_TOP: "borderRoundedTop",
    BORDER_ROUNDED_TOP_0: "borderRoundedTop0",
    BORDER_ROUNDED_TOP_1: "borderRoundedTop1",
    BORDER_ROUNDED_TOP_2: "borderRoundedTop2",
    BORDER_ROUNDED_TOP_3: "borderRoundedTop3",
    BORDER_ROUNDED_TOP_4: "borderRoundedTop4",
    BORDER_ROUNDED_TOP_5: "borderRoundedTop5",
    BORDER_ROUNDED_TOP_CIRCLE: "borderRoundedTopCircle",
    BORDER_ROUNDED_TOP_PILL: "borderRoundedTopPill",

    BORDER_ROUNDED_END: "borderRoundedEnd",
    BORDER_ROUNDED_END_0: "borderRoundedEnd0",
    BORDER_ROUNDED_END_1: "borderRoundedEnd1",
    BORDER_ROUNDED_END_2: "borderRoundedEnd2",
    BORDER_ROUNDED_END_3: "borderRoundedEnd3",
    BORDER_ROUNDED_END_4: "borderRoundedEnd4",
    BORDER_ROUNDED_END_5: "borderRoundedEnd5",
    BORDER_ROUNDED_END_CIRCLE: "borderRoundedEndCircle",
    BORDER_ROUNDED_END_PILL: "borderRoundedEndPill",

    BORDER_ROUNDED_BOTTOM: "borderRoundedBottom",
    BORDER_ROUNDED_BOTTOM_0: "borderRoundedBottom0",
    BORDER_ROUNDED_BOTTOM_1: "borderRoundedBottom1",
    BORDER_ROUNDED_BOTTOM_2: "borderRoundedBottom2",
    BORDER_ROUNDED_BOTTOM_3: "borderRoundedBottom3",
    BORDER_ROUNDED_BOTTOM_4: "borderRoundedBottom4",
    BORDER_ROUNDED_BOTTOM_5: "borderRoundedBottom5",
    BORDER_ROUNDED_BOTTOM_CIRCLE: "borderRoundedBottomCircle",
    BORDER_ROUNDED_BOTTOM_PILL: "borderRoundedBottomPill",

    BORDER_ROUNDED_START: "borderRoundedStart",
    BORDER_ROUNDED_START_0: "borderRoundedStart0",
    BORDER_ROUNDED_START_1: "borderRoundedStart1",
    BORDER_ROUNDED_START_2: "borderRoundedStart2",
    BORDER_ROUNDED_START_3: "borderRoundedStart3",
    BORDER_ROUNDED_START_4: "borderRoundedStart4",
    BORDER_ROUNDED_START_5: "borderRoundedStart5",
    BORDER_ROUNDED_START_CIRCLE: "borderRoundedStartCircle",
    BORDER_ROUNDED_START_PILL: "borderRoundedStartPill",

    BORDER_STYLE_NONE: "borderNone",
    BORDER_STYLE_DASHED: "borderDashed",
    BORDER_STYLE_DOTTED: "borderDotted",
    BORDER_STYLE_DOUBLE: "borderDouble",
    BORDER_STYLE_GROOVE: "borderGroove",
    BORDER_STYLE_HIDDEN: "borderHidden",
    BORDER_STYLE_INSET: "borderInset",
    BORDER_STYLE_OUTSET: "borderOutset",
    BORDER_STYLE_RIDGE: "borderRidge",
    BORDER_STYLE_SOLID: "borderSolid",
  },

  /**************************************************
   * Color
   *************************************************/
  COLOR: {
    TEXT_PRIMARY: "textPrimary",
    TEXT_PRIMARY_LIGHT: "textPrimaryLight",
    TEXT_PRIMARY_DARK: "textPrimaryDark",

    TEXT_SECONDARY: "textSecondary",
    TEXT_SECONDARY_LIGHT: "textSecondaryLight",
    TEXT_SECONDARY_DARK: "textSecondaryDark",

    TEXT_SUCCESS: "textSuccess",
    TEXT_SUCCESS_LIGHT: "textSuccessLight",
    TEXT_SUCCESS_DARK: "textSuccessDark",

    TEXT_ERROR: "textError",
    TEXT_ERROR_LIGHT: "textErrorLight",
    TEXT_ERROR_DARK: "textErrorDark",

    TEXT_WARNING: "textWarning",
    TEXT_WARNING_LIGHT: "textWarningLight",
    TEXT_WARNING_DARK: "textWarningDark",

    TEXT_INFO: "textInfo",
    TEXT_INFO_LIGHT: "textInfoLight",
    TEXT_INFO_DARK: "textInfoDark",

    TEXT_BLACK: "textBlack",
    TEXT_BLACK_50: "textBlack50",
    TEXT_WHITE: "textWhite",
    TEXT_WHITE_50: "textWhite50",

    TEXT_RESET: "textReset",

    TEXT_OPACITY_25: "textOpacity25",
    TEXT_OPACITY_50: "textOpacity50",
    TEXT_OPACITY_75: "textOpacity75",
    TEXT_OPACITY_100: "textOpacity100",
  },

  /**************************************************
   * Cursor
   *************************************************/
  CURSOR: {
    CURSOR_ALIAS: "cursorAlias",
    CURSOR_ALL_SCROLL: "cursorAllScroll",
    CURSOR_AUTO: "cursorAuto",
    CURSOR_CELL: "cursorCell",
    CURSOR_COL_RESIZE: "cursorColResize",
    CURSOR_CONTEXT_MENU: "cursorContextMenu",
    CURSOR_COPY: "cursorCopy",
    CURSOR_CROSSHAIR: "cursorCrosshair",
    CURSOR_DEFAULT: "cursorDefault",
    CURSOR_EW_RESIZE: "cursorEwResize",
    CURSOR_E_RESIZE: "cursorEResize",
    CURSOR_GRAB: "cursorGrab",
    CURSOR_GRABBING: "cursorGrabbing",
    CURSOR_HELP: "cursorHelp",
    CURSOR_MOVE: "cursorMove",
    CURSOR_N_RESIZE: "cursorNResize",
    CURSOR_NE_RESIZE: "cursorNeResize",
    CURSOR_NESW_RESIZE: "cursorNeswResize",
    CURSOR_INITIAL: "cursorInitial",
    CURSOR_NO_DROP: "cursorNoDrop",
    CURSOR_INHERIT: "cursorInherit",
    CURSOR_NONE: "cursorNone",
    CURSOR_NOT_ALLOWED: "cursorNotAllowed",
    CURSOR_NS_RESIZE: "cursorNsResize",
    CURSOR_NW_RESIZE: "cursorNwResize",
    CURSOR_NWSE_RESIZE: "cursorNwseResize",
    CURSOR_POINTER: "cursorPointer",
    CURSOR_PROGRESS: "cursorProgress",
    CURSOR_ROW_RESIZE: "cursorRowResize",
    CURSOR_S_RESIZE: "cursorSResize",
    CURSOR_SE_RESIZE: "cursorSeResize",
    CURSOR_SW_RESIZE: "cursorSwResize",
    CURSOR_TEXT: "cursorText",
    CURSOR_URL: "cursorURL",
    CURSOR_VERTICAL_TEXT: "cursorVerticalText",
    CURSOR_W_RESIZE: "cursorWResize",
    CURSOR_WAIT: "cursorWait",
    CURSOR_ZOOM_IN: "cursorZoomIn",
    CURSOR_ZOOM_OUT: "cursorZoomOut",
  },

  /**************************************************
   * Display
   *************************************************/
  DISPLAY: {
    INLINE: "displayInline",
    INLINE_BLOCK: "displayInlineBlock",
    BLOCK: "displayBlock",
    GRID: "displayGrid",
    TABLE: "displayTable",
    TABLE_ROW: "displayTableRow",
    TABLE_CELL: "displayTableCell",
    FLEX: "displayFlex",
    INLINE_FLEX: "displayInlineFlex",
    LIST_ITEM: "displayListItem",
    CONTENTS: "displayContent",
    INLINE_GRID: "displayInlineGrid",
    INLINE_TABLE: "displayInlineTable",
    RUN_IN: "displayRunIn",
    TABLE_CAPTION: "displayTableCaption",
    TABLE_COLUMN_GROUP: "displayTableColumnGroup",
    TABLE_Header_Group: "displayTableHeaderGroup",
    TABLE_ROW_GROUP: "displayTableRowGroup",
    TABLE_COLUMN: "dispalyTableColumn",
    INITIAL: "displayInitial",
    INHERIT: "displayInherit",
    NONE: "displayNone",

    SM: {
      INLINE: "smDisplayInline",
      INLINE_BLOCK: "smDisplayInlineBlock",
      BLOCK: "smDisplayBlock",
      GRID: "smDisplayGrid",
      TABLE: "smDisplayTable",
      TABLE_ROW: "smDisplayTableRow",
      TABLE_CELL: "smDisplayTableCell",
      FLEX: "smDisplayFlex",
      INLINE_FLEX: "smDisplayInlineFlex",
      LIST_ITEM: "smDisplayListItem",
      CONTENTS: "smDisplayContent",
      INLINE_GRID: "smDisplayInlineGrid",
      INLINE_TABLE: "smDisplayInlineTable",
      RUN_IN: "smDisplayRunIn",
      TABLE_CAPTION: "smsmDisplayTableCaption",
      TABLE_COLUMN_GROUP: "smDisplayTableColumnGroup",
      TABLE_Header_Group: "smDisplayTableHeaderGroup",
      TABLE_ROW_GROUP: "smDisplayTableRowGroup",
      TABLE_COLUMN: "smdispalyTableColumn",
      INITIAL: "smDisplayInitial",
      INHERIT: "smDisplayInherit",
      NONE: "smDisplayNone",
    },
    MD: {
      INLINE: "mdDisplayInline",
      INLINE_BLOCK: "mdDisplayInlineBlock",
      BLOCK: "mdDisplayBlock",
      GRID: "mdDisplayGrid",
      TABLE: "mdDisplayTable",
      TABLE_ROW: "mdDisplayTableRow",
      TABLE_CELL: "mdDisplayTableCell",
      FLEX: "mdDisplayFlex",
      INLINE_FLEX: "mdDisplayInlineFlex",
      LIST_ITEM: "mdDisplayListItem",
      CONTENTS: "mdDisplayContent",
      INLINE_GRID: "mdDisplayInlineGrid",
      INLINE_TABLE: "mddisplayInlineTable",
      RUN_IN: "mdDisplayRunIn",
      TABLE_CAPTION: "mdDisplayTableCaption",
      TABLE_COLUMN_GROUP: "mdDisplayTableColumnGroup",
      TABLE_Header_Group: "mdDisplayTableHeaderGroup",
      TABLE_ROW_GROUP: "mdDisplayTableRowGroup",
      TABLE_COLUMN: "mddispalyTableColumn",
      INITIAL: "mdDisplayInitial",
      INHERIT: "mdDisplayInherit",
      NONE: "mdDisplayNone",
    },
    LG: {
      INLINE: "lgDisplayInline",
      INLINE_BLOCK: "lgDisplayInlineBlock",
      BLOCK: "lgDisplayBlock",
      GRID: "lgDisplayGrid",
      TABLE: "lgDisplayTable",
      TABLE_ROW: "lgDisplayTableRow",
      TABLE_CELL: "lgDisplayTableCell",
      FLEX: "lgDisplayFlex",
      INLINE_FLEX: "lgDisplayInlineFlex",
      LIST_ITEM: "lgDisplayListItem",
      CONTENTS: "lgDisplayContent",
      INLINE_GRID: "lgDisplayInlineGrid",
      INLINE_TABLE: "lgDisplayInlineTable",
      RUN_IN: "lgDisplayRunIn",
      TABLE_CAPTION: "lgDisplayTableCaption",
      TABLE_COLUMN_GROUP: "lgDisplayTableColumnGroup",
      TABLE_Header_Group: "lgDisplayTableHeaderGroup",
      TABLE_ROW_GROUP: "lgDisplayTableRowGroup",
      TABLE_COLUMN: "lgDispalyTableColumn",
      INITIAL: "lgDisplayInitial",
      INHERIT: "lgDisplayInherit",
      NONE: "lgDisplayNone",
    },
    XL: {
      INLINE: "xxlDisplayInline",
      INLINE_BLOCK: "xlDisplayInlineBlock",
      BLOCK: "xlDisplayBlock",
      GRID: "xlDisplayGrid",
      TABLE: "xlDisplayTable",
      TABLE_ROW: "xlDisplayTableRow",
      TABLE_CELL: "xlDisplayTableCell",
      FLEX: "xlDisplayFlex",
      INLINE_FLEX: "xlDisplayInlineFlex",
      LIST_ITEM: "xlDisplayListItem",
      CONTENTS: "xlDisplayContent",
      INLINE_GRID: "xlDisplayInlineGrid",
      INLINE_TABLE: "xlDisplayInlineTable",
      RUN_IN: "xlDisplayRunIn",
      TABLE_CAPTION: "xlDisplayTableCaption",
      TABLE_COLUMN_GROUP: "xlDisplayTableColumnGroup",
      TABLE_Header_Group: "xlDisplayTableHeaderGroup",
      TABLE_ROW_GROUP: "xlDisplayTableRowGroup",
      TABLE_COLUMN: "dispalyTableColumn",
      INITIAL: "xlDisplayInitial",
      INHERIT: "xlDisplayInherit",
      NONE: "xlDisplayNone",
    },
    XXL: {
      INLINE: "xxlDisplayInline",
      INLINE_BLOCK: "xxlDisplayInlineBlock",
      BLOCK: "xxlDisplayBlock",
      GRID: "xxlDisplayGrid",
      TABLE: "xxlDisplayTable",
      TABLE_ROW: "xxlDisplayTableRow",
      TABLE_CELL: "xxlDisplayTableCell",
      FLEX: "xxlDisplayFlex",
      INLINE_FLEX: "xxlDisplayInlineFlex",
      LIST_ITEM: "xxldisplayListItem",
      CONTENTS: "xxldisplayContent",
      INLINE_GRID: "xxldisplayInlineGrid",
      INLINE_TABLE: "xxldisplayInlineTable",
      RUN_IN: "xxldisplayRunIn",
      TABLE_CAPTION: "xxldisplayTableCaption",
      TABLE_COLUMN_GROUP: "xxldisplayTableColumnGroup",
      TABLE_Header_Group: "xxldisplayTableHeaderGroup",
      TABLE_ROW_GROUP: "xxldisplayTableRowGroup",
      TABLE_COLUMN: "dispalyTableColumn",
      INITIAL: "xxldisplayInitial",
      INHERIT: "xxldisplayInherit",
      NONE: "xxlDisplayNone",
    },
  },

  /**************************************************
   * Flex
   *************************************************/
  FLEX: {
    DIRECTION_ROW: "flexDirectionRow",
    DIRECTION_COLUMN: "flexDirectionColumn",
    DIRECTION_ROW_REVERSE: "flexDirectionRowReverse",
    DIRECTION_COLUMN_REVERSE: "flexDirectionColumnReverse",
    FILL: "flexFill",
    FLEX_GROW_0: "flexGrow0",
    FLEX_GROW_1: "flexGrow1",
    FLEX_SHRINK_0: "flexShrink0",
    FLEX_SHRINK_1: "flexShrink1",
    FLEX_WRAP_WRAP: "flexWrapWrap",
    FLEX_WRAP_NO_WRAP: "flexWrapNoWrap",
    FLEX_WRAP_WRAP_REVERSE: "flexWrapWrapReverse",
    SM: {
      DIRECTION_ROW: "smFlexDirectionRow",
      DIRECTION_COLUMN: "smFlexDirectionColumn",
      DIRECTION_ROW_REVERSE: "smFlexDirectionRowReverse",
      DIRECTION_COLUMN_REVERSE: "smFlexDirectionColumnReverse",
      FILL: "smFlexFill",
      FLEX_GROW_0: "smFlexGrow0",
      FLEX_GROW_1: "smFlexGrow1",
      FLEX_SHRINK_0: "smFlexShrink0",
      FLEX_SHRINK_1: "smFlexShrink1",
      FLEX_WRAP_WRAP: "smFlexWrapWrap",
      FLEX_WRAP_NO_WRAP: "smFlexWrapNoWrap",
      FLEX_WRAP_WRAP_REVERSE: "smFlexWrapWrapReverse",
    },
    MD: {
      DIRECTION_ROW: "mdFlexDirectionRow",
      DIRECTION_COLUMN: "mdFlexDirectionColumn",
      DIRECTION_ROW_REVERSE: "mdFlexDirectionRowReverse",
      DIRECTION_COLUMN_REVERSE: "mdFlexDirectionColumnReverse",
      FILL: "mdFlexFill",
      FLEX_GROW_0: "mdFlexGrow0",
      FLEX_GROW_1: "mdFlexGrow1",
      FLEX_SHRINK_0: "mdFlexShrink0",
      FLEX_SHRINK_1: "mdFlexShrink1",
      FLEX_WRAP_WRAP: "mdFlexWrapWrap",
      FLEX_WRAP_NO_WRAP: "mdFlexWrapNoWrap",
      FLEX_WRAP_WRAP_REVERSE: "mdFlexWrapWrapReverse",
    },
    LG: {
      DIRECTION_ROW: "lgFlexDirectionRow",
      DIRECTION_COLUMN: "lgFlexDirectionColumn",
      DIRECTION_ROW_REVERSE: "lgFlexDirectionRowReverse",
      DIRECTION_COLUMN_REVERSE: "lgFlexDirectionColumnReverse",
      FILL: "lgFlexFill",
      FLEX_GROW_0: "lgFlexGrow0",
      FLEX_GROW_1: "lgFlexGrow1",
      FLEX_SHRINK_0: "lgFlexShrink0",
      FLEX_SHRINK_1: "lgFlexShrink1",
      FLEX_WRAP_WRAP: "lgFlexWrapWrap",
      FLEX_WRAP_NO_WRAP: "lgFlexWrapNoWrap",
      FLEX_WRAP_WRAP_REVERSE: "lgFlexWrapWrapReverse",
    },
    XL: {
      DIRECTION_ROW: "xlFlexDirectionRow",
      DIRECTION_COLUMN: "xlFlexDirectionColumn",
      DIRECTION_ROW_REVERSE: "xlFlexDirectionRowReverse",
      DIRECTION_COLUMN_REVERSE: "xlFlexDirectionColumnReverse",
      FILL: "xlFlexFill",
      FLEX_GROW_0: "xlFlexGrow0",
      FLEX_GROW_1: "xlFlexGrow1",
      FLEX_SHRINK_0: "xlFlexShrink0",
      FLEX_SHRINK_1: "xlFlexShrink1",
      FLEX_WRAP_WRAP: "xlFlexWrapWrap",
      FLEX_WRAP_NO_WRAP: "xlFlexWrapNoWrap",
      FLEX_WRAP_WRAP_REVERSE: "xlFlexWrapWrapReverse",
    },
    XXL: {
      DIRECTION_ROW: "xxlFlexDirectionRow",
      DIRECTION_COLUMN: "xxlFlexDirectionColumn",
      DIRECTION_ROW_REVERSE: "xxlFlexDirectionRowReverse",
      DIRECTION_COLUMN_REVERSE: "xxlFlexDirectionColumnReverse",
      FILL: "xxlFlexFill",
      FLEX_GROW_0: "xxlFlexGrow0",
      FLEX_GROW_1: "xxlFlexGrow1",
      FLEX_SHRINK_0: "xxlFlexShrink0",
      FLEX_SHRINK_1: "xxlFlexShrink1",
      FLEX_WRAP_WRAP: "xxlFlexWrapWrap",
      FLEX_WRAP_NO_WRAP: "xxlFlexWrapNoWrap",
      FLEX_WRAP_WRAP_REVERSE: "xxlFlexWrapWrapReverse",
    },
  },

  /**************************************************
   * Float
   *************************************************/
  FLOAT: {
    START: "floatStart",
    END: "floatEnd",
    NONE: "floatNone",
    SM: { START: "smFloatStart", END: "smFloatEnd", NONE: "smFloatNone" },
    MD: { START: "mdFloatStart", END: "mdFloatEnd", NONE: "mdFloatNone" },
    LG: { START: "lgFloatStart", END: "lgFloatEnd", NONE: "lgFloatNone" },
    XL: { START: "xlFloatStart", END: "xlFloatEnd", NONE: "xlFloatNone" },
    XXL: { START: "xxlFloatStart", END: "xxlFloatEnd", NONE: "xxlFloatNone" },
  },

  /**************************************************
   * Interactions
   *************************************************/
  INTERACTIONS: {
    USER_SELECT: {
      ALL: "userSelectAll",
      AUTO: "userSelectAuto",
      NONE: "userSelectNone",
    },
    POINTER_EVENT: {
      NONE: "peNone",
      AUTO: "peAuto",
    },
  },

  /**************************************************
   * Object Fit
   *************************************************/
  OBJECT_FIT: {
    CONTAIN: "objectFitContain",
    COVER: "objectFitCover",
    FILL: "objectFitFill",
    SCALE: "objectFitScale",
    NONE: "objectFitNone",
    SM: {
      CONTAIN: "smObjectFitContain",
      COVER: "smObjectFitCover",
      FILL: "smObjectFitFill",
      SCALE: "smObjectFitScale",
      NONE: "smObjectFitNone",
    },
    MD: {
      CONTAIN: "mdObjectFitContain",
      COVER: "mdObjectFitCover",
      FILL: "mdObjectFitFill",
      SCALE: "mdObjectFitScale",
      NONE: "mdObjectFitNone",
    },
    LG: {
      CONTAIN: "lgObjectFitContain",
      COVER: "lgObjectFitCover",
      FILL: "lgObjectFitFill",
      SCALE: "lgObjectFitScale",
      NONE: "lgObjectFitNone",
    },
    XL: {
      CONTAIN: "xlObjectFitContain",
      COVER: "xlObjectFitCover",
      FILL: "xlObjectFitFill",
      SCALE: "xlObjectFitScale",
      NONE: "xlObjectFitNone",
    },
    XXL: {
      CONTAIN: "xxlObjectFitContain",
      COVER: "xxlObjectFitCover",
      FILL: "xxlObjectFitFill",
      SCALE: "xxlObjectFitScale",
      NONE: "xxlObjectFitNone",
    },
  },
  /**************************************************
   * ASPECT_RATIO
   *************************************************/
  ASPECT_RATIO: {
    RATIO_16_9: "aspectRatio16By9",
    RATIO_9_16: "aspectRatio9By16",
    RATIO_20_9: "aspectRatio20By9",
    RATIO_9_20: "aspectRatio9By20",
    RATIO_3_2: "aspectRatio3By2",
    RATIO_2_3: "aspectRatio2By3",
    RATIO_4_3: "aspectRatio4By3",
    RATIO_3_4: "aspectRatio3By4",
    RATIO_25_9: "aspectRatio25By9",
    RATIO_9_25: "aspectRatio9By25",
    RATIO_21_9: "aspectRatio21By9",
    RATIO_9_21: "aspectRatio9By21",
    RATIO_1_1: "aspectRatio1By1",
  },

  /**************************************************
   * Opacity
   *************************************************/
  OPACITY: {
    OPACITY_0: "opacity0",
    OPACITY_5: "opacity5",
    OPACITY_10: "opacity10",
    OPACITY_15: "opacity15",
    OPACITY_20: "opacity20",
    OPACITY_25: "opacity25",
    OPACITY_30: "opacity30",
    OPACITY_35: "opacity35",
    OPACITY_40: "opacity40",
    OPACITY_45: "opacity45",
    OPACITY_50: "opacity50",
    OPACITY_55: "opacity55",
    OPACITY_60: "opacity60",
    OPACITY_65: "opacity65",
    OPACITY_70: "opacity70",
    OPACITY_75: "opacity75",
    OPACITY_80: "opacity80",
    OPACITY_85: "opacity85",
    OPACITY_90: "opacity90",
    OPACITY_95: "opacity95",
    OPACITY_100: "opacity100",
  },

  /**************************************************
   * Overflow
   *************************************************/
  OVERFLOW: {
    OVERFLOW_AUTO: "overflowAuto",
    OVERFLOW_HIDDEN: "overflowHidden",
    OVERFLOW_VISIBLE: "overflowVisible",
    OVERFLOW_SCROLL: "overflowScroll",
    OVERFLOW_X_AUTO: "overflowXAuto",
    OVERFLOW_X_HIDDEN: "overflowXHidden",
    OVERFLOW_X_VISIBLE: "overflowXVisible",
    OVERFLOW_X_SCROLL: "overflowXScroll",
    OVERFLOW_Y_AUTO: "overflowYAuto",
    OVERFLOW_Y_HIDDEN: "overflowYHidden",
    OVERFLOW_Y_VISIBLE: "overflowYVisible",
    OVERFLOW_Y_SCROLL: "overflowYScroll",
  },

  /**************************************************
   * Position
   *************************************************/
  POSITION: {
    POSITION_STATIC: "positionStatic",
    POSITION_RELATIVE: "positionRelative",
    POSITION_ABSOLUTE: "positionAbsolute",
    POSITION_FIXED: "positionFixed",
    POSITION_STICKY: "positionSticky",

    TOP_0: "top0",
    TOP_25: "top25",
    TOP_50: "top50",
    TOP_75: "top75",
    TOP_100: "top100",

    BOTTOM_0: "bottom0",
    BOTTOM_25: "bottom25",
    BOTTOM_50: "bottom50",
    BOTTOM_75: "bottom75",
    BOTTOM_100: "bottom100",

    START_0: "start0",
    START_25: "start25",
    START_50: "start50",
    START_75: "start75",
    START_100: "start100",

    END_0: "end0",
    END_25: "end25",
    END_50: "end50",
    END_75: "end75",
    END_100: "end100",

    TRANSLATE_MIDDLE: "translateMiddle",
    TRANSLATE_MIDDLE_X: "translateMiddleX",
    TRANSLATE_MIDDLE_Y: "translateMiddleY",

    FIXED_TOP: "fixedTop",
    FIXED_BOTTOM: "fixedBottom",
    STICKY_TOP: "stickyTop",
    STICKY_BOTTOM: "stickyBottom",
  },

  /**************************************************
   * Shadows
   *************************************************/
  SHADOW: {
    NORMAL: "shadow",
    SMALL: "shadowSm",
    LARGE: "shadowLg",
    NONE: "shadowNone",
  },

  /**************************************************
   * Transform
   *************************************************/
  TRANSFORM: {
    ROTATE: {
      ROTATE_15: "rotate15",
      ROTATE_30: "rotate30",
      ROTATE_45: "rotate45",
      ROTATE_60: "rotate60",
      ROTATE_75: "rotate75",
      ROTATE_90: "rotate90",
      ROTATE_120: "rotate120",
      ROTATE_180: "rotate180",
      ROTATE_270: "rotate270",

      ROTATE_N_15: "rotateN15",
      ROTATE_N_30: "rotateN30",
      ROTATE_N_45: "rotateN45",
      ROTATE_N_60: "rotateN60",
      ROTATE_N_75: "rotateN75",
      ROTATE_N_90: "rotateN90",
      ROTATE_N_120: "rotateN120",
      ROTATE_N_180: "rotateN180",
      ROTATE_N_270: "rotateN270",

      ROTATE_X_15: "rotateX15",
      ROTATE_X_45: "rotateX45",
      ROTATE_X_30: "rotateX30",
      ROTATE_X_60: "rotateX60",
      ROTATE_X_75: "rotateX75",
      ROTATE_X_90: "rotateX90",
      ROTATE_X_120: "rotateX120",
      ROTATE_X_180: "rotateX180",
      ROTATE_X_270: "rotateX270",

      ROTATE_X_N_15: "rotateXN15",
      ROTATE_X_N_30: "rotateXN30",
      ROTATE_X_N_45: "rotateXN45",
      ROTATE_X_N_60: "rotateXN60",
      ROTATE_X_N_75: "rotateXN75",
      ROTATE_X_N_90: "rotateXN90",
      ROTATE_X_N_120: "rotateXN120",
      ROTATE_X_N_145: "rotateXN145",
      ROTATE_X_N_180: "rotateXN180",
      ROTATE_X_N_270: "rotateXN270",

      ROTATE_Y_15: "rotateY15",
      ROTATE_Y_30: "rotateY30",
      ROTATE_Y_45: "rotateY45",
      ROTATE_Y_60: "rotateY60",
      ROTATE_Y_75: "rotateY75",
      ROTATE_Y_90: "rotateY90",
      ROTATE_Y_120: "rotateY120",
      ROTATE_Y_145: "rotateY145",
      ROTATE_Y_180: "rotateY180",
      ROTATE_Y_270: "rotateY270",

      ROTATE_Y_N_30: "rotateYN15",
      ROTATE_Y_N_15: "rotateYN30",
      ROTATE_Y_N_45: "rotateYN45",
      ROTATE_Y_N_60: "rotateYN60",
      ROTATE_Y_N_75: "rotateYN75",
      ROTATE_Y_N_90: "rotateYN90",
      ROTATE_Y_N_120: "rotateYN120",
      ROTATE_Y_N_145: "rotateYN145",
      ROTATE_Y_N_180: "rotateYN180",
      ROTATE_Y_N_270: "rotateYN270",
    },

    TRANSLATE_MIDDLE: "translateMiddle",
    TRANSLATE_MIDDLE_X: "translateMiddleX",
    TRANSLATE_MIDDLE_Y: "translateMiddleY",
  },

  /**************************************************
   * Sizing
   *************************************************/
  /*-------------------------------------------------
   * Width
   *-----------------------------------------------*/
  WIDTH: {
    W_25: "w25",
    W_50: "w50",
    W_75: "w75",
    W_100: "w100",
    W_AUTO: "wAuto",
    MAX_W_25: "maxW25",
    MAX_W_50: "maxW50",
    MAX_W_75: "maxW75",
    MAX_W_100: "maxW100",
    MIN_W_25: "minW25",
    MIN_W_50: "minW50",
    MIN_W_75: "minW75",
    MIN_W_100: "minW100",
    VW_25: "vw25",
    VW_50: "vw50",
    VW_75: "vw75",
    VW_100: "vw100",
    MAX_VW_25: "maxVw25",
    MAX_VW_50: "maxVw50",
    MAX_VW_75: "maxVw75",
    MAX_VW_100: "maxVw100",
    MIN_VW_25: "minVw25",
    MIN_VW_50: "minVw50",
    MIN_VW_75: "minVw75",
    MIN_VW_100: "minVw100",
  },

  /*-------------------------------------------------
   * Height
   *-----------------------------------------------*/
  HEIGHT: {
    H_25: "h25",
    H_50: "h50",
    H_75: "h75",
    H_100: "h100",
    H_AUTO: "hAuto",
    MAX_H_25: "maxH25",
    MAX_H_50: "maxH50",
    MAX_H_75: "maxH75",
    MAX_H_100: "maxH100",
    MIN_H_25: "minH25",
    MIN_H_50: "minH50",
    MIN_H_75: "minH75",
    MIN_H_100: "minH100",
    VH_25: "vh25",
    VH_50: "vh50",
    VH_75: "vh75",
    VH_100: "vh100",
    MAX_VH_25: "maxVh25",
    MAX_VH_50: "maxVh50",
    MAX_VH_75: "maxVh75",
    MAX_VH_100: "maxVh100",
    MIN_VH_25: "minVh25",
    MIN_VH_50: "minVh50",
    MIN_VH_75: "minVh75",
    MIN_VH_100: "minVh100",
  },

  /**************************************************
   * Spacing
   *************************************************/
  /*-------------------------------------------------
   * Padding
   *-----------------------------------------------*/
  PADDING: {
    P0: "p0",
    P1: "p1",
    P2: "p2",
    P3: "p3",
    P4: "p4",
    P5: "p5",
    PT0: "pt0",
    PT1: "pt1",
    PT2: "pt2",
    PT3: "pt3",
    PT4: "pt4",
    PT5: "pt5",
    PR0: "pr0",
    PR1: "pr1",
    PR2: "pr2",
    PR3: "pr3",
    PR4: "pr4",
    PR5: "pr5",
    PB0: "pb0",
    PB1: "pb1",
    PB2: "pb2",
    PB3: "pb3",
    PB4: "pb4",
    PB5: "pb5",
    PL0: "pl0",
    PL1: "pl1",
    PL2: "pl2",
    PL3: "pl3",
    PL4: "pl4",
    PL5: "pl5",
    PX0: "px0",
    PX1: "px1",
    PX2: "px2",
    PX3: "px3",
    PX4: "px4",
    PX5: "px5",
    PY0: "py0",
    PY1: "py1",
    PY2: "py2",
    PY3: "py3",
    PY4: "py4",
    PY5: "py5",
    SM: {
      P0: "smP0",
      P1: "smP1",
      P2: "smP2",
      P3: "smP3",
      P4: "smP4",
      P5: "smP5",
      PT0: "smPt0",
      PT1: "smPt1",
      PT2: "smPt2",
      PT3: "smPt3",
      PT4: "smPt4",
      PT5: "smPt5",
      PR0: "smPr0",
      PR1: "smPr1",
      PR2: "smPr2",
      PR3: "smPr3",
      PR4: "smPr4",
      PR5: "smPr5",
      PB0: "smPb0",
      PB1: "smPb1",
      PB2: "smPb2",
      PB3: "smPb3",
      PB4: "smPb4",
      PB5: "smPb5",
      PL0: "smPl0",
      PL1: "smPl1",
      PL2: "smPl2",
      PL3: "smPl3",
      PL4: "smPl4",
      PL5: "smPl5",
      PX0: "smPx0",
      PX1: "smPx1",
      PX2: "smPx2",
      PX3: "smPx3",
      PX4: "smPx4",
      PX5: "smPx5",
      PY0: "smPy0",
      PY1: "smPy1",
      PY2: "smPy2",
      PY3: "smPy3",
      PY4: "smPy4",
      PY5: "smPy5",
    },
    MD: {
      P0: "mdP0",
      P1: "mdP1",
      P2: "mdP2",
      P3: "mdP3",
      P4: "mdP4",
      P5: "mdP5",
      PT0: "mdPt0",
      PT1: "mdPt1",
      PT2: "mdPt2",
      PT3: "mdPt3",
      PT4: "mdPt4",
      PT5: "mdPt5",
      PR0: "mdPr0",
      PR1: "mdPr1",
      PR2: "mdPr2",
      PR3: "mdPr3",
      PR4: "mdPr4",
      PR5: "mdPr5",
      PB0: "mdPb0",
      PB1: "mdPb1",
      PB2: "mdPb2",
      PB3: "mdPb3",
      PB4: "mdPb4",
      PB5: "mdPb5",
      PL0: "mdPl0",
      PL1: "mdPl1",
      PL2: "mdPl2",
      PL3: "mdPl3",
      PL4: "mdPl4",
      PL5: "mdPl5",
      PX0: "mdPx0",
      PX1: "mdPx1",
      PX2: "mdPx2",
      PX3: "mdPx3",
      PX4: "mdPx4",
      PX5: "mdPx5",
      PY0: "mdPy0",
      PY1: "mdPy1",
      PY2: "mdPy2",
      PY3: "mdPy3",
      PY4: "mdPy4",
      PY5: "mdPy5",
    },
    LG: {
      P0: "lgP0",
      P1: "lgP1",
      P2: "lgP2",
      P3: "lgP3",
      P4: "lgP4",
      P5: "lgP5",
      PT0: "lgPt0",
      PT1: "lgPt1",
      PT2: "lgPt2",
      PT3: "lgPt3",
      PT4: "lgPt4",
      PT5: "lgPt5",
      PR0: "lgPr0",
      PR1: "lgPr1",
      PR2: "lgPr2",
      PR3: "lgPr3",
      PR4: "lgPr4",
      PR5: "lgPr5",
      PB0: "lgPb0",
      PB1: "lgPb1",
      PB2: "lgPb2",
      PB3: "lgPb3",
      PB4: "lgPb4",
      PB5: "lgPb5",
      PL0: "lgPl0",
      PL1: "lgPl1",
      PL2: "lgPl2",
      PL3: "lgPl3",
      PL4: "lgPl4",
      PL5: "lgPl5",
      PX0: "lgPx0",
      PX1: "lgPx1",
      PX2: "lgPx2",
      PX3: "lgPx3",
      PX4: "lgPx4",
      PX5: "lgPx5",
      PY0: "lgPy0",
      PY1: "lgPy1",
      PY2: "lgPy2",
      PY3: "lgPy3",
      PY4: "lgPy4",
      PY5: "lgPy5",
    },
    XL: {
      P0: "xlP0",
      P1: "xlP1",
      P2: "xlP2",
      P3: "xlP3",
      P4: "xlP4",
      P5: "xlP5",
      PT0: "xlPt0",
      PT1: "xlPt1",
      PT2: "xlPt2",
      PT3: "xlPt3",
      PT4: "xlPt4",
      PT5: "xlPt5",
      PR0: "xlPr0",
      PR1: "xlPr1",
      PR2: "xlPr2",
      PR3: "xlPr3",
      PR4: "xlPr4",
      PR5: "xlPr5",
      PB0: "xlPb0",
      PB1: "xlPb1",
      PB2: "xlPb2",
      PB3: "xlPb3",
      PB4: "xlPb4",
      PB5: "xlPb5",
      PL0: "xlPl0",
      PL1: "xlPl1",
      PL2: "xlPl2",
      PL3: "xlPl3",
      PL4: "xlPl4",
      PL5: "xlPl5",
      PX0: "xlPx0",
      PX1: "xlPx1",
      PX2: "xlPx2",
      PX3: "xlPx3",
      PX4: "xlPx4",
      PX5: "xlPx5",
      PY0: "xlPy0",
      PY1: "xlPy1",
      PY2: "xlPy2",
      PY3: "xlPy3",
      PY4: "xlPy4",
      PY5: "xlPy5",
    },
    XXL: {
      P0: "xxlP0",
      P1: "xxlP1",
      P2: "xxlP2",
      P3: "xxlP3",
      P4: "xxlP4",
      P5: "xxlP5",
      PT0: "xxlPt0",
      PT1: "xxlPt1",
      PT2: "xxlPt2",
      PT3: "xxlPt3",
      PT4: "xxlPt4",
      PT5: "xxlPt5",
      PR0: "xxlPr0",
      PR1: "xxlPr1",
      PR2: "xxlPr2",
      PR3: "xxlPr3",
      PR4: "xxlPr4",
      PR5: "xxlPr5",
      PB0: "xxlPb0",
      PB1: "xxlPb1",
      PB2: "xxlPb2",
      PB3: "xxlPb3",
      PB4: "xxlPb4",
      PB5: "xxlPb5",
      PL0: "xxlPl0",
      PL1: "xxlPl1",
      PL2: "xxlPl2",
      PL3: "xxlPl3",
      PL4: "xxlPl4",
      PL5: "xxlPl5",
      PX0: "xxlPx0",
      PX1: "xxlPx1",
      PX2: "xxlPx2",
      PX3: "xxlPx3",
      PX4: "xxlPx4",
      PX5: "xxlPx5",
      PY0: "xxlPy0",
      PY1: "xxlPy1",
      PY2: "xxlPy2",
      PY3: "xxlPy3",
      PY4: "xxlPy4",
      PY5: "xxlPy5",
    },
  },

  /*-------------------------------------------------
   * Margin
   *-----------------------------------------------*/
  MARGIN: {
    M0: "m0",
    M1: "m1",
    M2: "m2",
    M3: "m3",
    M4: "m4",
    M5: "m5",
    M_AUTO: "mAuto",
    MT0: "mt0",
    MT1: "mt1",
    MT2: "mt2",
    MT3: "mt3",
    MT4: "mt4",
    MT5: "mt5",
    MT_AUTO: "mtAuto",
    MR0: "mr0",
    MR1: "mr1",
    MR2: "mr2",
    MR3: "mr3",
    MR4: "mr4",
    MR5: "mr5",
    MR_AUTO: "mrAuto",
    MB0: "mb0",
    MB1: "mb1",
    MB2: "mb2",
    MB3: "mb3",
    MB4: "mb4",
    MB5: "mb5",
    MB_AUTO: "mbAuto",
    ML0: "ml0",
    ML1: "ml1",
    ML2: "ml2",
    ML3: "ml3",
    ML4: "ml4",
    ML5: "ml5",
    ML_AUTO: "mlAuto",
    MX0: "mx0",
    MX1: "mx1",
    MX2: "mx2",
    MX3: "mx3",
    MX4: "mx4",
    MX5: "mx5",
    MX_AUTO: "mxAuto",
    MY0: "my0",
    MY1: "my1",
    MY2: "my2",
    MY3: "my3",
    MY4: "my4",
    MY5: "my5",
    MY_AUTO: "myAuto",
    M_N1: "mN1",
    M_N2: "mN2",
    M_N3: "mN3",
    M_N4: "mN4",
    M_N5: "mN5",
    MT_N1: "mtN1",
    MT_N2: "mtN2",
    MT_N3: "mtN3",
    MT_N4: "mtN4",
    MT_N5: "mtN5",
    MR_N1: "mrN1",
    MR_N2: "mrN2",
    MR_N3: "mrN3",
    MR_N4: "mrN4",
    MR_N5: "mrN5",
    MB_N1: "mbN1",
    MB_N2: "mbN2",
    MB_N3: "mbN3",
    MB_N4: "mbN4",
    MB_N5: "mbN5",
    ML_N1: "mlN1",
    ML_N2: "mlN2",
    ML_N3: "mlN3",
    ML_N4: "mlN4",
    ML_N5: "mlN5",
    MX_N1: "mxN1",
    MX_N2: "mxN2",
    MX_N3: "mxN3",
    MX_N4: "mxN4",
    MX_N5: "mxN5",
    MY_N1: "myN1",
    MY_N2: "myN2",
    MY_N3: "myN3",
    MY_N4: "myN4",
    MY_N5: "myN5",
    SM: {
      M0: "smM0",
      M1: "smM1",
      M2: "smM2",
      M3: "smM3",
      M4: "smM4",
      M5: "smM5",
      M_AUTO: "smMAuto",
      MT0: "smMt0",
      MT1: "smMt1",
      MT2: "smMt2",
      MT3: "smMt3",
      MT4: "smMt4",
      MT5: "smMt5",
      MT_AUTO: "smMtAuto",
      MR0: "smMr0",
      MR1: "smMr1",
      MR2: "smMr2",
      MR3: "smMr3",
      MR4: "smMr4",
      MR5: "smMr5",
      MR_AUTO: "smMrAuto",
      MB0: "smMb0",
      MB1: "smMb1",
      MB2: "smMb2",
      MB3: "smMb3",
      MB4: "smMb4",
      MB5: "smMb5",
      MB_AUTO: "smMbAuto",
      ML0: "smMl0",
      ML1: "smMl1",
      ML2: "smMl2",
      ML3: "smMl3",
      ML4: "smMl4",
      ML5: "smMl5",
      ML_AUTO: "smMlAuto",
      MX0: "smMx0",
      MX1: "smMx1",
      MX2: "smMx2",
      MX3: "smMx3",
      MX4: "smMx4",
      MX5: "smMx5",
      MX_AUTO: "smMxAuto",
      MY0: "smMy0",
      MY1: "smMy1",
      MY2: "smMy2",
      MY3: "smMy3",
      MY4: "smMy4",
      MY5: "smMy5",
      MY_AUTO: "smMyAuto",
      M_N1: "smMN1",
      M_N2: "smMN2",
      M_N3: "smMN3",
      M_N4: "smMN4",
      M_N5: "smMN5",
      MT_N1: "smMtN1",
      MT_N2: "smMtN2",
      MT_N3: "smMtN3",
      MT_N4: "smMtN4",
      MT_N5: "smMtN5",
      MR_N1: "smMrN1",
      MR_N2: "smMrN2",
      MR_N3: "smMrN3",
      MR_N4: "smMrN4",
      MR_N5: "smMrN5",
      MB_N1: "smMbN1",
      MB_N2: "smMbN2",
      MB_N3: "smMbN3",
      MB_N4: "smMbN4",
      MB_N5: "smMbN5",
      ML_N1: "smMlN1",
      ML_N2: "smMlN2",
      ML_N3: "smMlN3",
      ML_N4: "smMlN4",
      ML_N5: "smMlN5",
      MX_N1: "smMxN1",
      MX_N2: "smMxN2",
      MX_N3: "smMxN3",
      MX_N4: "smMxN4",
      MX_N5: "smMxN5",
      MY_N1: "smMyN1",
      MY_N2: "smMyN2",
      MY_N3: "smMyN3",
      MY_N4: "smMyN4",
      MY_N5: "smMyN5",
    },
    MD: {
      M0: "mdM0",
      M1: "mdM1",
      M2: "mdM2",
      M3: "mdM3",
      M4: "mdM4",
      M5: "mdM5",
      M_AUTO: "mdMAuto",
      MT0: "mdMt0",
      MT1: "mdMt1",
      MT2: "mdMt2",
      MT3: "mdMt3",
      MT4: "mdMt4",
      MT5: "mdMt5",
      MT_AUTO: "mdMtAuto",
      MR0: "mdMr0",
      MR1: "mdMr1",
      MR2: "mdMr2",
      MR3: "mdMr3",
      MR4: "mdMr4",
      MR5: "mdMr5",
      MR_AUTO: "mdMrAuto",
      MB0: "mdMb0",
      MB1: "mdMb1",
      MB2: "mdMb2",
      MB3: "mdMb3",
      MB4: "mdMb4",
      MB5: "mdMb5",
      MB_AUTO: "mdMbAuto",
      ML0: "mdMl0",
      ML1: "mdMl1",
      ML2: "mdMl2",
      ML3: "mdMl3",
      ML4: "mdMl4",
      ML5: "mdMl5",
      ML_AUTO: "mdMlAuto",
      MX0: "mdMx0",
      MX1: "mdMx1",
      MX2: "mdMx2",
      MX3: "mdMx3",
      MX4: "mdMx4",
      MX5: "mdMx5",
      MX_AUTO: "mdMxAuto",
      MY0: "mdMy0",
      MY1: "mdMy1",
      MY2: "mdMy2",
      MY3: "mdMy3",
      MY4: "mdMy4",
      MY5: "mdMy5",
      MY_AUTO: "mdMyAuto",
      M_N1: "mdMN1",
      M_N2: "mdMN2",
      M_N3: "mdMN3",
      M_N4: "mdMN4",
      M_N5: "mdMN5",
      MT_N1: "mdMtN1",
      MT_N2: "mdMtN2",
      MT_N3: "mdMtN3",
      MT_N4: "mdMtN4",
      MT_N5: "mdMtN5",
      MR_N1: "mdMrN1",
      MR_N2: "mdMrN2",
      MR_N3: "mdMrN3",
      MR_N4: "mdMrN4",
      MR_N5: "mdMrN5",
      MB_N1: "mdMbN1",
      MB_N2: "mdMbN2",
      MB_N3: "mdMbN3",
      MB_N4: "mdMbN4",
      MB_N5: "mdMbN5",
      ML_N1: "mdMlN1",
      ML_N2: "mdMlN2",
      ML_N3: "mdMlN3",
      ML_N4: "mdMlN4",
      ML_N5: "mdMlN5",
      MX_N1: "mdMxN1",
      MX_N2: "mdMxN2",
      MX_N3: "mdMxN3",
      MX_N4: "mdMxN4",
      MX_N5: "mdMxN5",
      MY_N1: "mdMyN1",
      MY_N2: "mdMyN2",
      MY_N3: "mdMyN3",
      MY_N4: "mdMyN4",
      MY_N5: "mdMyN5",
    },
    LG: {
      M0: "lgM0",
      M1: "lgM1",
      M2: "lgM2",
      M3: "lgM3",
      M4: "lgM4",
      M5: "lgM5",
      M_AUTO: "lgMAuto",
      MT0: "lgMt0",
      MT1: "lgMt1",
      MT2: "lgMt2",
      MT3: "lgMt3",
      MT4: "lgMt4",
      MT5: "lgMt5",
      MT_AUTO: "lgMtAuto",
      MR0: "lgMr0",
      MR1: "lgMr1",
      MR2: "lgMr2",
      MR3: "lgMr3",
      MR4: "lgMr4",
      MR5: "lgMr5",
      MR_AUTO: "lgMrAuto",
      MB0: "lgMb0",
      MB1: "lgMb1",
      MB2: "lgMb2",
      MB3: "lgMb3",
      MB4: "lgMb4",
      MB5: "lgMb5",
      MB_AUTO: "lgMbAuto",
      ML0: "lgMl0",
      ML1: "lgMl1",
      ML2: "lgMl2",
      ML3: "lgMl3",
      ML4: "lgMl4",
      ML5: "lgMl5",
      ML_AUTO: "lgMlAuto",
      MX0: "lgMx0",
      MX1: "lgMx1",
      MX2: "lgMx2",
      MX3: "lgMx3",
      MX4: "lgMx4",
      MX5: "lgMx5",
      MX_AUTO: "lgMxAuto",
      MY0: "lgMy0",
      MY1: "lgMy1",
      MY2: "lgMy2",
      MY3: "lgMy3",
      MY4: "lgMy4",
      MY5: "lgMy5",
      MY_AUTO: "lgMyAuto",
      M_N1: "lgMN1",
      M_N2: "lgMN2",
      M_N3: "lgMN3",
      M_N4: "lgMN4",
      M_N5: "lgMN5",
      MT_N1: "lgMtN1",
      MT_N2: "lgMtN2",
      MT_N3: "lgMtN3",
      MT_N4: "lgMtN4",
      MT_N5: "lgMtN5",
      MR_N1: "lgMrN1",
      MR_N2: "lgMrN2",
      MR_N3: "lgMrN3",
      MR_N4: "lgMrN4",
      MR_N5: "lgMrN5",
      MB_N1: "lgMbN1",
      MB_N2: "lgMbN2",
      MB_N3: "lgMbN3",
      MB_N4: "lgMbN4",
      MB_N5: "lgMbN5",
      ML_N1: "lgMlN1",
      ML_N2: "lgMlN2",
      ML_N3: "lgMlN3",
      ML_N4: "lgMlN4",
      ML_N5: "lgMlN5",
      MX_N1: "lgMxN1",
      MX_N2: "lgMxN2",
      MX_N3: "lgMxN3",
      MX_N4: "lgMxN4",
      MX_N5: "lgMxN5",
      MY_N1: "lgMyN1",
      MY_N2: "lgMyN2",
      MY_N3: "lgMyN3",
      MY_N4: "lgMyN4",
      MY_N5: "lgMyN5",
    },
    XL: {
      M0: "xlM0",
      M1: "xlM1",
      M2: "xlM2",
      M3: "xlM3",
      M4: "xlM4",
      M5: "xlM5",
      M_AUTO: "xlMAuto",
      MT0: "xlMt0",
      MT1: "xlMt1",
      MT2: "xlMt2",
      MT3: "xlMt3",
      MT4: "xlMt4",
      MT5: "xlMt5",
      MT_AUTO: "xlMtAuto",
      MR0: "xlMr0",
      MR1: "xlMr1",
      MR2: "xlMr2",
      MR3: "xlMr3",
      MR4: "xlMr4",
      MR5: "xlMr5",
      MR_AUTO: "xlMrAuto",
      MB0: "xlMb0",
      MB1: "xlMb1",
      MB2: "xlMb2",
      MB3: "xlMb3",
      MB4: "xlMb4",
      MB5: "xlMb5",
      MB_AUTO: "xlMbAuto",
      ML0: "xlMl0",
      ML1: "xlMl1",
      ML2: "xlMl2",
      ML3: "xlMl3",
      ML4: "xlMl4",
      ML5: "xlMl5",
      ML_AUTO: "xlMlAuto",
      MX0: "xlMx0",
      MX1: "xlMx1",
      MX2: "xlMx2",
      MX3: "xlMx3",
      MX4: "xlMx4",
      MX5: "xlMx5",
      MX_AUTO: "xlMxAuto",
      MY0: "xlMy0",
      MY1: "xlMy1",
      MY2: "xlMy2",
      MY3: "xlMy3",
      MY4: "xlMy4",
      MY5: "xlMy5",
      MY_AUTO: "xlMyAuto",
      M_N1: "xlMN1",
      M_N2: "xlMN2",
      M_N3: "xlMN3",
      M_N4: "xlMN4",
      M_N5: "xlMN5",
      MT_N1: "xlMtN1",
      MT_N2: "xlMtN2",
      MT_N3: "xlMtN3",
      MT_N4: "xlMtN4",
      MT_N5: "xlMtN5",
      MR_N1: "xlMrN1",
      MR_N2: "xlMrN2",
      MR_N3: "xlMrN3",
      MR_N4: "xlMrN4",
      MR_N5: "xlMrN5",
      MB_N1: "xlMbN1",
      MB_N2: "xlMbN2",
      MB_N3: "xlMbN3",
      MB_N4: "xlMbN4",
      MB_N5: "xlMbN5",
      ML_N1: "xlMlN1",
      ML_N2: "xlMlN2",
      ML_N3: "xlMlN3",
      ML_N4: "xlMlN4",
      ML_N5: "xlMlN5",
      MX_N1: "xlMxN1",
      MX_N2: "xlMxN2",
      MX_N3: "xlMxN3",
      MX_N4: "xlMxN4",
      MX_N5: "xlMxN5",
      MY_N1: "xlMyN1",
      MY_N2: "xlMyN2",
      MY_N3: "xlMyN3",
      MY_N4: "xlMyN4",
      MY_N5: "xlMyN5",
    },
    XXL: {
      M0: "xxlM0",
      M1: "xxlM1",
      M2: "xxlM2",
      M3: "xxlM3",
      M4: "xxlM4",
      M5: "xxlM5",
      M_AUTO: "xxlMAuto",
      MT0: "xxlMt0",
      MT1: "xxlMt1",
      MT2: "xxlMt2",
      MT3: "xxlMt3",
      MT4: "xxlMt4",
      MT5: "xxlMt5",
      MT_AUTO: "xxlMtAuto",
      MR0: "xxlMr0",
      MR1: "xxlMr1",
      MR2: "xxlMr2",
      MR3: "xxlMr3",
      MR4: "xxlMr4",
      MR5: "xxlMr5",
      MR_AUTO: "xxlMrAuto",
      MB0: "xxlMb0",
      MB1: "xxlMb1",
      MB2: "xxlMb2",
      MB3: "xxlMb3",
      MB4: "xxlMb4",
      MB5: "xxlMb5",
      MB_AUTO: "xxlMbAuto",
      ML0: "xxlMl0",
      ML1: "xxlMl1",
      ML2: "xxlMl2",
      ML3: "xxlMl3",
      ML4: "xxlMl4",
      ML5: "xxlMl5",
      ML_AUTO: "xxlMlAuto",
      MX0: "xxlMx0",
      MX1: "xxlMx1",
      MX2: "xxlMx2",
      MX3: "xxlMx3",
      MX4: "xxlMx4",
      MX5: "xxlMx5",
      MX_AUTO: "xxlMxAuto",
      MY0: "xxlMy0",
      MY1: "xxlMy1",
      MY2: "xxlMy2",
      MY3: "xxlMy3",
      MY4: "xxlMy4",
      MY5: "xxlMy5",
      MY_AUTO: "xxlMyAuto",
      M_N1: "xxlMN1",
      M_N2: "xxlMN2",
      M_N3: "xxlMN3",
      M_N4: "xxlMN4",
      M_N5: "xxlMN5",
      MT_N1: "xxlMtN1",
      MT_N2: "xxlMtN2",
      MT_N3: "xxlMtN3",
      MT_N4: "xxlMtN4",
      MT_N5: "xxlMtN5",
      MR_N1: "xxlMrN1",
      MR_N2: "xxlMrN2",
      MR_N3: "xxlMrN3",
      MR_N4: "xxlMrN4",
      MR_N5: "xxlMrN5",
      MB_N1: "xxlMbN1",
      MB_N2: "xxlMbN2",
      MB_N3: "xxlMbN3",
      MB_N4: "xxlMbN4",
      MB_N5: "xxlMbN5",
      ML_N1: "xxlMlN1",
      ML_N2: "xxlMlN2",
      ML_N3: "xxlMlN3",
      ML_N4: "xxlMlN4",
      ML_N5: "xxlMlN5",
      MX_N1: "xxlMxN1",
      MX_N2: "xxlMxN2",
      MX_N3: "xxlMxN3",
      MX_N4: "xxlMxN4",
      MX_N5: "xxlMxN5",
      MY_N1: "xxlMyN1",
      MY_N2: "xxlMyN2",
      MY_N3: "xxlMyN3",
      MY_N4: "xxlMyN4",
      MY_N5: "xxlMyN5",
    },
  },

  /*-------------------------------------------------
   * Gap
   *-----------------------------------------------*/
  GAP: {
    GAP_0: "gap0",
    GAP_1: "gap1",
    GAP_2: "gap2",
    GAP_3: "gap3",
    GAP_4: "gap4",
    GAP_5: "gap5",
    ROW_GAP_0: "rowGap0",
    ROW_GAP_1: "rowGap1",
    ROW_GAP_2: "rowGap2",
    ROW_GAP_3: "rowGap3",
    ROW_GAP_4: "rowGap4",
    ROW_GAP_5: "rowGap5",
    COL_GAP_0: "colGap0",
    COL_GAP_1: "colGap1",
    COL_GAP_2: "colGap2",
    COL_GAP_3: "colGap3",
    COL_GAP_4: "colGap4",
    COL_GAP_5: "colGap5",

    SM: {
      GAP_0: "smGap0",
      GAP_1: "smGap1",
      GAP_2: "smGap2",
      GAP_3: "smGap3",
      GAP_4: "smGap4",
      GAP_5: "smGap5",
      ROW_GAP_0: "smRowGap0",
      ROW_GAP_1: "smRowGap1",
      ROW_GAP_2: "smRowGap2",
      ROW_GAP_3: "smRowGap3",
      ROW_GAP_4: "smRowGap4",
      ROW_GAP_5: "smRowGap5",
      COL_GAP_0: "smColGap0",
      COL_GAP_1: "smColGap1",
      COL_GAP_2: "smColGap2",
      COL_GAP_3: "smColGap3",
      COL_GAP_4: "smColGap4",
      COL_GAP_5: "smColGap5",
    },
    MD: {
      GAP_0: "mdGap0",
      GAP_1: "mdGap1",
      GAP_2: "mdGap2",
      GAP_3: "mdGap3",
      GAP_4: "mdGap4",
      GAP_5: "mdGap5",
      ROW_GAP_0: "mdRowGap0",
      ROW_GAP_1: "mdRowGap1",
      ROW_GAP_2: "mdRowGap2",
      ROW_GAP_3: "mdRowGap3",
      ROW_GAP_4: "mdRowGap4",
      ROW_GAP_5: "mdRowGap5",
      COL_GAP_0: "mdColGap0",
      COL_GAP_1: "mdColGap1",
      COL_GAP_2: "mdColGap2",
      COL_GAP_3: "mdColGap3",
      COL_GAP_4: "mdColGap4",
      COL_GAP_5: "mdColGap5",
    },
    LG: {
      GAP_0: "lgGap0",
      GAP_1: "lgGap1",
      GAP_2: "lgGap2",
      GAP_3: "lgGap3",
      GAP_4: "lgGap4",
      GAP_5: "lgGap5",
      ROW_GAP_0: "lgRowGap0",
      ROW_GAP_1: "lgRowGap1",
      ROW_GAP_2: "lgRowGap2",
      ROW_GAP_3: "lgRowGap3",
      ROW_GAP_4: "lgRowGap4",
      ROW_GAP_5: "lgRowGap5",
      COL_GAP_0: "lgColGap0",
      COL_GAP_1: "lgColGap1",
      COL_GAP_2: "lgColGap2",
      COL_GAP_3: "lgColGap3",
      COL_GAP_4: "lgColGap4",
      COL_GAP_5: "lgColGap5",
    },
    XL: {
      GAP_0: "xlGap0",
      GAP_1: "xlGap1",
      GAP_2: "xlGap2",
      GAP_3: "xlGap3",
      GAP_4: "xlGap4",
      GAP_5: "xlGap5",
      ROW_GAP_0: "xlRowGap0",
      ROW_GAP_1: "xlRowGap1",
      ROW_GAP_2: "xlRowGap2",
      ROW_GAP_3: "xlRowGap3",
      ROW_GAP_4: "xlRowGap4",
      ROW_GAP_5: "xlRowGap5",
      COL_GAP_0: "xlColGap0",
      COL_GAP_1: "xlColGap1",
      COL_GAP_2: "xlColGap2",
      COL_GAP_3: "xlColGap3",
      COL_GAP_4: "xlColGap4",
      COL_GAP_5: "xlColGap5",
    },
    XXL: {
      GAP_0: "xxlGap0",
      GAP_1: "xxlGap1",
      GAP_2: "xxlGap2",
      GAP_3: "xxlGap3",
      GAP_4: "xxlGap4",
      GAP_5: "xxlGap5",
      ROW_GAP_0: "xxlRowGap0",
      ROW_GAP_1: "xxlRowGap1",
      ROW_GAP_2: "xxlRowGap2",
      ROW_GAP_3: "xxlRowGap3",
      ROW_GAP_4: "xxlRowGap4",
      ROW_GAP_5: "xxlRowGap5",
      COL_GAP_0: "xxlColGap0",
      COL_GAP_1: "xxlColGap1",
      COL_GAP_2: "xxlColGap2",
      COL_GAP_3: "xxlColGap3",
      COL_GAP_4: "xxlColGap4",
      COL_GAP_5: "xxlColGap5",
    },
  },

  /**************************************************
   * Text
   *************************************************/
  TEXT: {
    TEXT_START: "textStart",
    TEXT_END: "textEnd",
    TEXT_CENTER: "textCenter",
    TEXT_JUSTIFY: "textJustify",

    TEXT_WEIGHT_LIGHTER: "textWeightLighter",
    TEXT_WEIGHT_LIGHT: "textWeightLight",
    TEXT_WEIGHT_NORMAL: "textWeightNormal",
    TEXT_WEIGHT_MEDIUM: "textWeightMedium",
    TEXT_WEIGHT_SEMIBOLD: "textWeightSemibold",
    TEXT_WEIGHT_BOLD: "textWeightBold",
    TEXT_WEIGHT_BOLDER: "textWeightBolder",

    TEXT_STYLE_ITALIC: "textStyleItalic",
    TEXT_STYLE_NORMAL: "textStyleNormal",

    TEXT_DECORATION_NONE: "textDecorationNone",
    TEXT_DECORATION_UNDERLINE: "textDecorationUnderline",
    TEXT_DECORATION_LINE_THROUGH: "textDecorationLineThrough",

    TEXT_TRANSFORM_LOWERCASE: "textLowercase",
    TEXT_TRANSFORM_UPPERCASE: "textUppercase",
    TEXT_TRANSFORM_CAPITALIZE: "textCapitalize",

    TEXT_WRITING_MODE_TOP_TO_BOTTOM: "textTopToBottom",
    TEXT_WRITING_MODE_BOTTOM_TO_TOP: "textBottomToTop",

    TEXT_WRAP: "textWrap",
    TEXT_NOWRAP: "textNowrap",
    TEXT_BREAK: "textBreak",
    TEXT_TRUNCATE: "textTruncate",

    WORD_SPACING_NORMAL: "wordSpacingNormal",
    WORD_SPACING_1: "wordSpacing1",
    WORD_SPACING_2: "wordSpacing2",
    WORD_SPACING_3: "wordSpacing3",
    WORD_SPACING_4: "wordSpacing4",
    WORD_SPACING_5: "wordSpacing5",

    LINEHEIGHT_NORMAL: "lineHeightNormal", // default numeric value is 1.6
    LINEHEIGHT_2: "lineHeight2", // the line height will be relative and multipled to the font size.
    LINEHEIGHT_3: "lineHeight3", // // the line height will be relative and multipled to the font size.
    LINEHEIGHT_INITIAL: "lineHeightInitial", // Sets this property to its default value
    LINEHEIGHT_INHERIT: "lineHeightInherit", // Inherits this property from its parent element.

    SM: {
      TEXT_START: "smTextStart",
      TEXT_END: "smTextEnd",
      TEXT_CENTER: "smTextCenter",
      TEXT_JUSTIFY: "smTextJustify",
    },
    MD: {
      TEXT_START: "mdTextStart",
      TEXT_END: "mdTextEnd",
      TEXT_CENTER: "mdTextCenter",
      TEXT_JUSTIFY: "mdTextJustify",
    },
    LG: {
      TEXT_START: "lgTextStart",
      TEXT_END: "lgTextEnd",
      TEXT_CENTER: "lgTextCenter",
      TEXT_JUSTIFY: "lgTextJustify",
    },
    XL: {
      TEXT_START: "xlTextStart",
      TEXT_END: "xlTextEnd",
      TEXT_CENTER: "xlTextCenter",
      TEXT_JUSTIFY: "xlTextJustify",
    },
    XXL: {
      TEXT_START: "xxlTextStart",
      TEXT_END: "xxlTextEnd",
      TEXT_CENTER: "xxlTextCenter",
      TEXT_JUSTIFY: "xxlTextJustify",
    },
  },

  /**************************************************
   * Vertical Align
   *************************************************/
  VERTICAL_ALIGN: {
    BASELINE: "alignBaseline",
    TOP: "alignTop",
    MIDDLE: "alignMiddle",
    BOTTOM: "alignBottom",
    TEXT_BOTTOM: "alignTextBottom",
    TEXT_TOP: "alignTextTop",
  },

  /**************************************************
   * Visibility
   *************************************************/
  VISIBILITY: {
    VISIBLE: "visible",
    INVISIBLE: "invisible",
  },
  /**************************************************
   * zindex
   *************************************************/
  Z_INDEX: {
    Z_N1: "zN1",
    Z_0: "z0",
    Z_1: "z1",
    Z_2: "z2",
    Z_3: "z3",
  },
  /**************************************************
   * listStyle
   *************************************************/
  LIST_STYLE: {
    CJK_HEAVENLY_STEM: "listStyleCjkHeavenlyStem",
    ARABIC_INDIC: "listStyleArabicIndic",
    DISC: "listStyleDisc",
    CIRCLE: "listStyleCircle",
    SQUARE: "listStyleSquare",
    DECIMAL: "listStyleDecimal",
    DECIMAL_LEADING_ZERO: "listStyleDecimalLeadingZero",
    ARMENIAN: "listStyleArmenian",
    AUTO: "listStyleAuto",
    BENGALI: "listStyleBengali",
    CAMBODIAN: "listStyleCambodian",
    CJK_EARTHLY_BRANCH: "listStyleCjkEarthlyBranch",
    CJK_IDEOGRAPHIC: "listStyleCjkIdeographic",
    DEVANAGARI: "listStyleDevanagari",
    ETHIOPIC_HALEHAME: "listStyleEthiopicHalehame",
    ETHIOPIC_HALEHAME_AM: "listStyleEthiopicHalehameAm",
    ETHIOPIC_HALEHAME_TI_ER: "listStyleEthiopicHalehameTiEr",
    ETHIOPIC_HALEHAME_TI_ET: "listStyleEthiopicHalehameTiEt",
    GEORGIAN: "listStyleGeorgian",
    GUJARATI: "listStyleGujarati",
    HANGUL: "listStyleHangul",
    HANGUL_CONSONANT: "listStyleHangulConsonant",
    HEBREW: "listStyleHebrew",
    HIRAGANA: "listStyleHiragana",
    HIRAGANAIROHA: "listStyleHiraganaIroha",
    INSIDE: "listStyleInside",
    KANNADA: "listStyleKannada",
    KATAKANA: "listStyleKatakana",
    KATAKANA_IROHA: "listStyleKatakanaIroha",
    KHMER: "listStyleKhmer",
    KOREAN_HANJA_FORMAL: "listStyleKoreanHanjaFormal",
    KOREAN_HANGUL_FORMAL: "listStyleKoreanHangulFormal",
    KOREAN_HANJA_INFORMAL: "listStyleKoreanHanjaInformal",
    LAO: "listStyleLao",
    LOWER_ALPHA: "listStyleLowerAlpha",
    LOWER_ARMENIAN: "listStyleLowerArmenian",
    LOWER_LATIN: "listStyleLowerLatin",
    LOWER_GREEK: "listStyleLowerGreek",
    LOWER_ROMAN: "listStyleLowerRoman",
    MALAYALAM: "listStyleMalayalam",
    MONGOLIAN: "listStyleMongolian",
    MYANMAR: "listStyleMyanmar",
    ORIYA: "listStyleOriya",
    OUTSIDE: "listStyleOutside",
    PERSIAN: "listStylePersian",
    SIMP_CHINESE_FORMAL: "listStyleSimpChineseFormal",
    SIMP_CHINESE_INFORMAL: "listStyleSimpChineseInFormal",
    TELUGU: "listStyleTelugu",
    THAI: "listStyleThai",
    TIBETAN: "listStyleTibetan",
    TRAD_CHINESE_FORMAL: "listStyleTradChineseFormal",
    TRAD_CHINESE_INFORMAL: "listStyleTradChineseInformal",
    UPPER_ALPHA: "listStyleUpperAlpha",
    UPPER_ARMENIAN: "listStyleUpperArmenian",
    UPPER_LATIN: "listStyleUpperLatin",
    UPPER_ROMAN: "listStyleUpperRoman",
    URDU: "listStyleUrdu",
    INHERIT: "listStyleInherit",
    INITIAL: "listStyleInitial",
    REVERT: "listStyleRevert",
    REVERT_LAYER: "listStyleRevertLayer",
    UNSET: "listStyleUnset",
    NONE: "listStyleNone",
  },
};

export default UtilityClasses;
